trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'myreactapp'
  dockerRegistryServiceConnection: 'lnePritishServiceConnection'  # The name of your service connection
  dockerRepository: 'lneReactRepo'  # The repository name in your ACR
  dockerImageTag: '$(Build.BuildId)'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(dockerRepository)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(dockerImageTag)
